collections:
- faqs
- features
- features_dev
- features_devops
- features_enterprise
- policies
- events

# Build settings
markdown:    kramdown
highlighter: rouge
kramdown:
  auto_ids:       true
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
